"""add document pages

Revision ID: d8f40dd46876
Revises: 6e1b7e3c8d63
Create Date: 2026-06-23 21:05:27.441387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8f40dd46876'
down_revision: Union[str, Sequence[str], None] = '6e1b7e3c8d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_pages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_version_id', 'page_number', name='uq_document_pages_version_page')
    )
    op.create_index(op.f('ix_document_pages_document_version_id'), 'document_pages', ['document_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_pages_document_version_id'), table_name='document_pages')
    op.drop_table('document_pages')
    # ### end Alembic commands ###
